[package]
name = "token_arbitrage_detection"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.5.4", features = ["full", "node-bindings"] }
dotenv = "0.15"
revm = { version = "17.1.0", features = ["alloydb"] }
tokio = { version = "1.40.0", features = ["full"] }
